import { StyleSheet } from 'react-native';
import { elevation, fontSizes, radii, spacing, ThemeColors } from '../../theme/tokens';

// One sheet for the chat screen and the components split out of it
// (MessageBubble, ChatDecorations) - they share most of their look, and
// splitting the sheet itself would mean guessing which rules each needs.
export const makeStyles = (colors: ThemeColors) =>
  StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.paper },
  content: { flex: 1, width: '100%', alignSelf: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
  },
  backButton: { paddingHorizontal: 4, paddingVertical: 4 },
  headerIdentity: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  headerNameBlock: { flex: 1 },
  callButton: { paddingHorizontal: 4, paddingVertical: 4 },
  headerName: { fontWeight: '700', fontSize: fontSizes.body, color: colors.ink },
  headerStatus: { fontSize: fontSizes.caption, fontWeight: '600', color: colors.sage },
  headerStatusOffline: { fontSize: fontSizes.caption, fontWeight: '600', color: colors.smoke },
  offlineBanner: {
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    paddingVertical: 6,
    borderRadius: radii.md,
    backgroundColor: colors.danger,
    alignItems: 'center',
  },
  offlineBannerText: { color: colors.white, fontSize: fontSizes.caption, fontWeight: '700' },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: colors.paper2,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.line,
  },
  searchInput: { flex: 1, fontSize: fontSizes.body, color: colors.ink, padding: 0 },
  searchEmptyText: {
    textAlign: 'center',
    color: colors.smoke,
    marginTop: spacing.xxl,
    fontSize: fontSizes.body,
  },
  searchResultRow: {
    paddingHorizontal: spacing.lg,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
  },
  searchResultSender: { fontWeight: '700', fontSize: fontSizes.footnote, color: colors.ink, marginBottom: 2 },
  searchResultSnippet: { fontSize: fontSizes.footnote, color: colors.smoke },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: colors.paper,
    borderRadius: radii.lg,
    padding: spacing.lg,
    ...elevation.lg,
  },
  modalTitle: { fontSize: fontSizes.bodyLg, fontWeight: '700', color: colors.ink, marginBottom: 6 },
  modalMessage: { fontSize: fontSizes.footnote, color: colors.smoke, marginBottom: spacing.md },
  forwardList: { maxHeight: 320 },
  forwardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.line,
  },
  forwardName: { flex: 1, fontSize: fontSizes.body, color: colors.ink },
  reportReason: {
    paddingVertical: 13,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.line,
  },
  reportReasonText: { fontSize: fontSizes.body, color: colors.ink },
  reportCancel: {
    marginTop: spacing.md,
    paddingVertical: 11,
    borderRadius: radii.pill,
    backgroundColor: colors.paper2,
    alignItems: 'center',
  },
  reportCancelText: { fontSize: fontSizes.body, fontWeight: '700', color: colors.smoke },
  loadError: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.xxl,
  },
  loadErrorTitle: { color: colors.ink, fontWeight: '700', fontSize: fontSizes.body },
  loadErrorHint: { color: colors.smoke, fontSize: fontSizes.footnote, textAlign: 'center' },
  loadErrorButton: {
    marginTop: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingVertical: 9,
    borderRadius: radii.pill,
    backgroundColor: colors.ember,
  },
  loadErrorButtonText: { color: colors.white, fontWeight: '700', fontSize: fontSizes.body },
  list: { flex: 1, paddingHorizontal: 12 },
  listArea: { flex: 1 },
  rowMine: { alignItems: 'flex-end', marginVertical: 4 },
  // Messages inside a run sit closer together than separate remarks do.
  rowJoined: { marginTop: 2 },
  historySkeleton: { flex: 1, justifyContent: 'flex-end', padding: spacing.md },
  rowTheirs: { alignItems: 'flex-start', marginVertical: 4 },
  bubble: {
    padding: 11,
    paddingHorizontal: 15,
    borderRadius: radii.bubble,
  },
  mediaBubble: {
    padding: 4,
    borderRadius: 18,
  },
  media: {
    width: 220,
    height: 220,
    borderRadius: 14,
  },
  mediaLoading: {
    backgroundColor: colors.line,
    justifyContent: 'center',
    alignItems: 'center',
  },
  audioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minWidth: 200,
  },
  callLogRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  waveform: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  waveformBar: {
    width: 2.5,
    borderRadius: 1.5,
  },
  fileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    maxWidth: 220,
  },
  fileName: { flex: 1, fontWeight: '600' },
  iconCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconCircleMine: { backgroundColor: colors.white },
  iconCircleTheirs: { backgroundColor: colors.ember },
  bubblePending: { opacity: 0.55 },
  bubbleHighlighted: { borderWidth: 3, borderColor: colors.sage },
  spinner: { marginTop: spacing.xl },
  historyLoading: { marginVertical: spacing.md },
  senderLabel: {
    fontSize: fontSizes.caption,
    fontWeight: '700',
    color: colors.smoke,
    marginBottom: 2,
    marginLeft: 4,
  },
  bubbleTextMine: { color: colors.white, fontSize: fontSizes.body, lineHeight: 20 },
  bubbleTextTheirs: { color: colors.ink, fontSize: fontSizes.body, lineHeight: 20 },
  editedTag: { fontSize: fontSizes.micro, color: colors.smoke, marginTop: 2 },
  linkText: { textDecorationLine: 'underline' },
  jumpToLatest: {
    position: 'absolute',
    right: spacing.lg,
    bottom: 88,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.paper2,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  jumpBadge: {
    position: 'absolute',
    top: -6,
    right: -4,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    paddingHorizontal: 5,
    backgroundColor: colors.ember,
    alignItems: 'center',
    justifyContent: 'center',
  },
  jumpBadgeText: { fontSize: fontSizes.micro, fontWeight: '700', color: colors.white },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
    gap: spacing.xs,
    marginTop: 2,
  },
  metaTextMine: { fontSize: fontSizes.micro, color: colors.white, opacity: 0.75 },
  metaTextTheirs: { fontSize: fontSizes.micro, color: colors.smoke },
  mentionMine: { fontWeight: '700', color: colors.white },
  mentionTheirs: { fontWeight: '700', color: colors.ember },
  statusMuted: { opacity: 0.75 },
  statusRead: { opacity: 1 },
  dayDivider: { alignItems: 'center', marginVertical: spacing.md },
  dayDividerText: {
    fontSize: fontSizes.caption,
    fontWeight: '700',
    color: colors.smoke,
    backgroundColor: colors.paper2,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radii.pill,
    overflow: 'hidden',
  },
  replyQuote: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 7,
    paddingVertical: 5,
    paddingRight: 8,
    marginBottom: 6,
    borderRadius: 8,
    overflow: 'hidden',
  },
  replyQuoteMine: { backgroundColor: 'rgba(255, 255, 255, 0.16)' },
  replyQuoteTheirs: { backgroundColor: colors.line },
  replyQuoteBar: { width: 3, borderRadius: 2 },
  replyQuoteBarMine: { backgroundColor: 'rgba(255, 255, 255, 0.7)' },
  replyQuoteBarTheirs: { backgroundColor: colors.ember },
  // Deliberately not flex:1 - this sits in a shrink-to-fit bubble (sized
  // to its widest content, capped by bubbleMaxWidth), and a flex:1 child
  // of a row whose own container isn't already a resolved width collapses
  // to ~0 rather than sharing the row's space, which was truncating the
  // quoted snippet down to just an ellipsis. Letting it size naturally
  // (like bubbleTextMine/Theirs below already do) lets the outer
  // maxWidth cap do the truncating only when actually necessary.
  replyQuoteContent: {},
  replyQuoteSenderMine: { fontSize: fontSizes.caption, fontWeight: '700', color: colors.white },
  replyQuoteSenderTheirs: { fontSize: fontSizes.caption, fontWeight: '700', color: colors.ember },
  replyQuoteTextMine: { fontSize: fontSizes.caption, color: 'rgba(255, 255, 255, 0.85)' },
  replyQuoteTextTheirs: { fontSize: fontSizes.caption, color: colors.smoke },
  reactionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 4,
    gap: 4,
  },
  reactionPill: {
    flexDirection: 'row',
    backgroundColor: colors.paper2,
    borderRadius: radii.lg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  reactionPillMine: { borderColor: colors.ember },
  reactionPillText: { fontSize: fontSizes.footnote },
  seenAvatar: { marginTop: 4, flexDirection: 'row', gap: 2 },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.smoke,
  },
  editingBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    backgroundColor: colors.paper2,
  },
  editingBarText: { fontSize: fontSizes.caption, color: colors.smoke },
  editingBarCancel: { fontSize: fontSizes.caption, color: colors.ember, fontWeight: '600' },
  replyBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    backgroundColor: colors.paper2,
    gap: spacing.md,
  },
  replyBarText: { flex: 1 },
  replyBarLabel: { fontSize: fontSizes.caption, fontWeight: '700', color: colors.ember },
  replyBarSnippet: { fontSize: fontSizes.caption, color: colors.smoke, marginTop: 1 },
  mentionList: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.line,
    paddingVertical: spacing.xs,
  },
  mentionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  mentionName: { flexShrink: 1, fontSize: fontSizes.body, fontWeight: '600', color: colors.ink },
  mentionUsername: { flexShrink: 1, fontSize: fontSizes.footnote, color: colors.smoke },
  composer: {
    flexDirection: 'row',
    padding: spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.line,
    alignItems: 'center',
  },
  attachButton: {
    paddingHorizontal: 8,
    paddingVertical: 8,
    marginRight: 4,
  },
  recordingIndicator: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  recordingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.danger,
  },
  recordingTime: { fontSize: fontSizes.body, color: colors.ink, fontWeight: '600' },
  input: {
    flex: 1,
    maxHeight: 120,
    backgroundColor: colors.paper2,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radii.xl,
    paddingHorizontal: spacing.lg,
    paddingVertical: 11,
    marginRight: spacing.sm,
    color: colors.ink,
    fontSize: fontSizes.body,
  },
  sendButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.ember,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
